<?php

namespace Skeletor;

class Palette_Customizer
{
	/**
	 * Action bound to after_setup_theme. Used to initialize this module.
	 *
	 * @return void
	 */
	public static function setup()
	{
		add_action(
			'customize_controls_enqueue_scripts',
			[__CLASS__, 'customize_controls_enqueue_scripts']
		);

		add_action(
			'customize_register',
			[__CLASS__, 'customize_register_palette']
		);

		add_action(
			'wp_head',
			[__CLASS__, 'custom_palette_inline_css']
		);
	}

	/**
	 * Action bound to customize_controls_enqueue_scripts. Used to enqueue
	 * the custom css and javascript used in the controls
	 *
	 * @return void
	 */
	public static function customize_controls_enqueue_scripts()
	{
		wp_enqueue_script(
			'skeletor-customize-palette',
			sprintf('%s/assets/customizer.js', plugin_dir_url(__FILE__)),
			filemtime(__DIR__ . '/assets/customizer.js')
		);

		wp_enqueue_style(
			'skeletor-customize-palette',
			sprintf('%s/assets/customizer.css', plugin_dir_url(__FILE__)),
			filemtime(__DIR__ . '/assets/customizer.css')
		);
	}

	/**
	 * Action callback bound to wp_head. This will output the inline css
	 * generated by any palette customizations.
	 *
	 * @return void
	 */
	public static function custom_palette_inline_css()
	{
		$palette = get_option('skeletor_theme_palette');
		if (!$palette) {
			return;
		}

		echo '<style id="skeletor-custom-palette-inline-css">body {';
		foreach ($palette as $key => $color) {
			printf('--wp--custom--colors--%s: %s;', $key, $color);
		}
		echo '}</style>';
	}

	/**
	 * Returns Customizer::$abstract_palette after passing it through a
	 * filter named `skeletor_abstract_palette`
	 *
	 * @return array
	 */
	private static function get_abstract_palette()
	{
		$global_settings = wp_get_global_settings();
		$abstract_palette = [];

		$light_palette = $global_settings['custom']['colors']['light'];
		foreach ($light_palette as $slug => $color) {
			$slug = _wp_to_kebab_case($slug);
			$abstract_palette[] = [
				'label'   => $slug,
				'slug'    => "light--{$slug}",
				'default' => $color,
			];
		}

		$dark_palette = $global_settings['custom']['colors']['dark'];
		foreach ($dark_palette as $slug => $color) {
			$slug = _wp_to_kebab_case($slug);
			$abstract_palette[] = [
				'label'   => "{$slug} (dark)",
				'slug'    => "dark--{$slug}",
				'default' => $color,
			];
		}

		return apply_filters(
			'skeletor_abstract_palette',
			$abstract_palette
		);
	}

	/**
	 * Returns the capability required to use the Customizer. The result is
	 * passed through a filter named `skeletor_customize_capability`.
	 *
	 * @return string
	 */
	private static function get_capability()
	{
		return apply_filters(
			'skeletor_customize_palette_capability',
			'edit_theme_options'
		);
	}

	/**
	 * Setup the "Skeletor Palette" customizer section and the options inside
	 *
	 * @param WP_Customize_Manager $wp_customize
	 * @return void
	 */
	public static function customize_register_palette($wp_customize)
	{
		$wp_customize->add_section('skeletor_palette', array(
			'title'    => __('Skeletor Palette', 'skeletor'),
			'priority' => 120,
		));

		$palette = self::get_abstract_palette();
		$capability = self::get_capability();

		foreach ($palette as $color) {
			if (!isset($color['label']) || !isset($color['slug'])) {
				continue;
			}

			$setting = sprintf('skeletor_theme_palette[%s]', $color['slug']);
			$setting_opts = [
				'capability' => $capability,
				'type'       => 'option',
			];

			if (isset($color['default'])) {
				$setting_opts['default'] = $color['default'];
			}

			$wp_customize->add_setting($setting, $setting_opts);

			$label = ucwords(str_replace('-', ' ', $color['label']));
			$label = str_replace('Bg', 'Background', $label);
			$label = apply_filters('skeletor_customize_palette_color_label', $label, $color);
			$wp_customize->add_control(new Customize_Variable_Color_Control(
				$wp_customize,
				$color['slug'],
				[
					'label'    => $label,
					'section'  => 'skeletor_palette',
					'settings' => $setting,
				]
			));
		}
	}
}

add_action('after_setup_theme', ['Skeletor\Palette_Customizer', 'setup']);
